### ISSUE TITLE
broken/incorrect links on website

### ISSUE THREAD

**Issue by aschetti** [JackEdTaylor/SIPS2021#1]
Hi @JackEdTaylor,
I followed this workshop at SIPS2021, it was very well organized and extremely useful... thanks so much for making and maintaining `LexOPS`!
While adapting your example code to an old stimulus set, I found a couple of bugs on the website that you might want to look into:

* [this page](https://jackedtaylor.github.io/SIPS2021/iw_02_multiple_controls.html) leads to 404
* [this page](https://jackedtaylor.github.io/SIPS2021/iw_05_factorial_designs.html) redirects to the [wrong page](https://jackedtaylor.github.io/SIPS2021/iw_03_more_than_2_conds.html)

All the other pages seem to be working fine.

Hope it's not too time-consuming to fix these issues... thanks again!

**Comment by JackEdTaylor** [comment]
Hi @aschetti, and thank you for this!

I think these are fixed by https://github.com/JackEdTaylor/SIPS2021/commit/73e88b0a19906e4492fec37a31f734265f082424. The first was a typo in the address and I think the second just had the wrong title on the page.

Thanks again!

**Comment by aschetti** [comment]
Thanks for your quick reply and fix!
